export const macronutrientsData = [
  {
    name: 'Carbohydrates',
    key: 'carbohydrates',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'Net Carbs',
    key: 'net_carbs',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'Fiber',
    key: 'fiber',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'Fats',
    key: 'fats',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'Saturated',
    key: 'saturated',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'MUFA',
    key: 'mufa',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'PUFA',
    key: 'pufa',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'PUFA ω-3',
    key: 'pufa_w3',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'PUFA ω-6',
    key: 'pufa_w6',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
  {
    name: 'Protein',
    key: 'protein',
    value: '',
    unitOfMeasurement: 'g',
    percentageOfTotal: 0,
  },
];