export const micronutrientsData = [
  {
    name: 'VitaminA RAE',
    key: 'vit_a_rae',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin A',
    key: 'vit_a',
    value: '',
    unitOfMeasurement: 'IU',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin C',
    key: 'vit_c',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin D',
    key: 'vit_d',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin E',
    key: 'vit_e',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin K',
    key: 'vit_k',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B1',
    key: 'vit_b1',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B2',
    key: 'vit_b2',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B3',
    key: 'vit_b3',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B5',
    key: 'vit_b5',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B6',
    key: 'vit_b6',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B9',
    key: 'vit_b9',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Vitamin B12',
    key: 'vit_b12',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Choline',
    key: 'choline',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Copper',
    key: 'copper',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Fluoride',
    key: 'fluoride',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Iron',
    key: 'iron',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Magnesium',
    key: 'magnesium',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Manganese',
    key: 'manganese',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Phosphoru',
    key: 'phosphoru',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Potassium',
    key: 'potassium',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Selenium',
    key: 'selenium',
    value: '',
    unitOfMeasurement: 'µg',
    percentageOfTotal: 0,
  },
  {
    name: 'Sodium',
    key: 'sodium',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
  {
    name: 'Zinc',
    key: 'zinc',
    value: '',
    unitOfMeasurement: 'mg',
    percentageOfTotal: 0,
  },
];
